config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|ja/ do
    root "books#index"
    resources :profiles
    resources :books do
      resource :user_books, only: [:create, :destroy]
    end

    devise_for :users, controllers: {
        registrations: "users/registrations", 
        sessions:      "users/sessions",
     }
    resources :users, except: [:new, :create]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update destroy]
  before_action :set_locale
  before_action :honnin?, only: %i[edit update destroy]
  # skip_before_action :authenticate_user!, only: :show これで書き方はあってることを確認。

  def index
    @profiles = Profile.page(params[:page]).per(10)#マジックナンバーになる。。
    @time = Time.now
  end
  
  def show
  end
  
  def new
    @profile = Profile.new
  end
  
  def create
     @profile = Profile.new(profile_params)
     #@profile = current_user.profiles.new(profile_params)
     if @profile.save
       redirect_to @profile, notice: t("directory.flash.create")
     else
       render :new
     end
  end

  def edit
    #@profile = Profile.find(params[:id])
    # redirect_to(root_url) unless @profile == current_profile
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: t("directory.flash.update")
    else
      render :edit
    end
  end
  # 一応作っとくが管理者以外使えないようにする。
  def destroy
    @profile.destroy
    redirect_to profiles_url, alert: t("directory.flash.destroy")
  end

  private
    def honnin?
      # redirect_to root_url,notice: t("directory.flash.update") unless @profile == current_profile
      #redirect_to root_url, alert: "本人以外はできません" unless @profile == current_profile # これでdestroyもリダイレクトできる。
    end
    def set_profile
      #@profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :zip_code, :address, :introduction)
    end
end

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>
<%= form_with(model: @profile, local: true) do |form| %>
  <%# <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%#= t("errors.template.header", model: Profile, count: @profile.errors.count) %></h2>
      <ul>
        <%# @profile.errors.full_messages.each do |message| %>
          <li><%#= message %></li>
        <%# end %>
      </ul>
    </div>
  <%# end %> 

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :introduction%>
    <%= form.text_area :introduction, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, autofocus: true,class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

<% @profiles.each do |profile| %>
  <br><%= profile.id %><br>
  <%= profile.name %><br>
  <td><%= l(profile.created_at, format: :short) %></td>
       <td><%= link_to t("directory.link.Show"), profile %></td>
       <td><%= link_to t("directory.link.Destroy"), profile, method: :delete, data: { confirm: t("directorymodal.confirm") } %></td>
<% end %>
<div class="paginate mt-4"><%= paginate @profiles %></div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

<%= form_with(model: @profile, local: true) do |form| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("errors.template.header", model: Profile, count: @profile.errors.count) %></h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :introduction%>
    <%= form.text_area :introduction, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, autofocus: true,class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

<h1><%= Profile.human_attribute_name(:name) %> :<%= "#{@profile.name}" %></h1>
<p><%= Profile.human_attribute_name(:address) %>  : <%= @profile.address %></p>
<p><%= Profile.human_attribute_name(:zip_code) %> : <%= @profile.zip_code %></p>
<p><%= Profile.human_attribute_name(:introduction) %> : <%= @profile.introduction %></p>
<%# 自分以外編集できないようにする。 %>
  <%#= link_to t("directory.link.Edit"), edit_profile_path(@profile) %> |
  <%#= link_to "Edit password", user_profile_registration_path, class: "navbar-link" %>