config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|ja/ do
    root "books#index"
    resources :profiles
    resources :books do
      resource :user_books, only: [:create, :destroy]
    end

    devise_for :users, controllers: {
        registrations: "users/registrations", 
        sessions:      "users/sessions",
     }
    resources :users, except: [:new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books
  has_many :profiles

  validates :name, presence: true
  validates :address, length: { maximum: 80 }
  validates :introduction, length: { maximum: 500 }
  # validates :zip_code,  length: {in: 4..10}#inにするとnilでもエラーになる。新規登録ページで郵便番号の登録が4文字以上必要となりエラーになる為考え直し。
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # 動作確認用
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # とりあえず動きの確認用に
  # protected
  # def after_update_path_for(resource)
  #   user_path(id: current_user.id)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :set_locale
  before_action :honnin?, only: %i[edit update destroy]
  # skip_before_action :authenticate_user!, only: :show これで書き方はあってることを確認。

  def index
    @users = User.page(params[:page]).per(10)#マジックナンバーになる。。
    @time = Time.now
  end

  def show
    @book_count = @user.books.size
  end

  def edit
    # @user = User.find(params[:id])
    # redirect_to(root_url) unless @user == current_user
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t("directory.flash.update")
    else
      render :edit
    end
  end
  # 一応作っとくが管理者以外使えないようにする。
  def destroy
    @user.destroy
    redirect_to users_url, alert: t("directory.flash.destroy")
  end

  private
    def honnin?
      # redirect_to root_url,notice: t("directory.flash.update") unless @user == current_user
      redirect_to root_url, alert: "本人以外はできません" unless @user == current_user # これでdestroyもリダイレクトできる。
    end
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name, :zip_code, :address, :introduction)
    end
end

app/views/users/edit.html.erb
editページ
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("errors.template.header", model: @user, count: @user.errors.count) %></h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction, autofocus: true, class: "form-control", autocomplete: "introduction" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary " %>
  </div>
<% end %>

app/views/users/index.html.erb
indexページ
destroyリンクは管理者だけに表示

<% @users.each do |user| %>
  <br><%= user.id %><br>
  <%= user.name %><br>
  <%= user.email %><br>
  <td><%= l(user.created_at, format: :short) %></td>
       <td><%= link_to t("directory.link.Show"), user %></td>
       <td><%= link_to t("directory.link.Destroy"), user, method: :delete, data: { confirm: t("directorymodal.confirm") } %></td>
<% end %>
<div class="paginate mt-4"><%= paginate @users %></div>

app/views/users/show.html.erb
<h1><%= User.human_attribute_name(:name) %> :<%= "#{@user.name}" %></h1>
<p><%= User.human_attribute_name(:email) %> : <%= @user.email %></p>
<p><%= User.human_attribute_name(:address) %>  : <%= @user.address %></p>
<p><%= User.human_attribute_name(:zip_code) %> : <%= @user.zip_code %></p>
<p><%= User.human_attribute_name(:introduction) %> : <%= @user.introduction %></p>
<p>投稿した本の件数：<%=@book_count %><p>
<%# 自分以外編集できないようにする。 %>
<% if current_user == @user %>
  <%= link_to t("directory.link.Edit"), edit_user_path(@user) %> |
  <%= link_to "Edit password", edit_user_registration_path, class: "navbar-link" %>
  <%= link_to "Edit profile", edit_profile_path, class: "navbar-link" %>
<% end %>